##########################################################################################################################
# File automatically-generated by STM32forVSCode
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# MAIN
######################################
MAIN = main

######################################
# target.
######################################
TARGET = PSU_V2

######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization	: O0 - O1 - Og - Os - O2 - O3
OPT = -Og -freorder-blocks-algorithm=stc -falign-loops -falign-labels -falign-jumps -falign-functions
#-fprefetch-loop-arrays is the one fucking up the program when using O2 or higher (O3 & Ofast) 

#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/$(MAIN).c \
Core/Src/miniprintf.c \
Core/Src/printf.c \
Core/Src/dac_i2c.c \
Core/Src/usart_pc.c \
Core/Src/usart_STM2.c \
Core/Src/i2c_oled.c \
SSD1306/ssd1306/ssd1306.c \
SSD1306/ssd1306/ssd1306_fonts.c \
SSD1306/ssd1306/ssd1306_tests.c

CPP_SOURCES = \


# ASM sources
ASM_SOURCES =  \
#startup_stm32f767xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.

ifdef GCC_PATH
CXX = $(GCC_PATH)/$(PREFIX)g++
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CXX = $(PREFIX)g++
CC = $(PREFIX)gcc -Wno-error=format-truncation
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-d16 #remove -sp-d16 for double precision

# float-abi
FLOAT-ABI = -mfloat-abi=hard -fsingle-precision-constant

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DSTM32F4 \
-DSTM32F411xx 


# AS includes
AS_INCLUDES = \

# C includes
C_INCLUDES =  \
-I../libopencm3-master/include \
-I../libopencm3-master/include/libopencmsis \
-I../libopencm3-master/include/libopencm3/stm32 \
-I../libopencm3-master/include/libopencm3/stm32/common \
-I../libopencm3-master/include/libopencm3/stm32/f4 \
-I../STMems_Standard_C_drivers \
-ICore/Inc \
-IDrivers/CMSIS/Include \
-ISSD1306/ssd1306


# compile gcc flags
ASFLAGS = --verbose $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wno-incompatible-pointer-types -Wno-implicit-int -Wno-implicit-function-declaration -Wno-return-mismatch -Wno-int-conversion -fdata-sections -ffunction-sections

CFLAGS = --verbose $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wno-incompatible-pointer-types -Wno-implicit-int -Wno-implicit-function-declaration -Wno-return-mismatch -Wno-int-conversion -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information (Removed warning)
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)" 

CXXFLAGS?=
CXXFLAGS += -feliminate-unused-debug-types

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = stm32f411.ld

# libraries
LIBS = -lc -lm -l:libopencm3_stm32f4.a
LIBDIR = -L../libopencm3-master/lib

LDFLAGS = $(MCU) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of cpp program objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(CPP_SOURCES:.cpp=.o)))
vpath %.cpp $(sort $(dir $(CPP_SOURCES)))
# list of C objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.cpp Makefile | $(BUILD_DIR) 
	$(CXX) -c $(CXXFLAGS) $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.cpp=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir $@

#######################################
# flash
#######################################
flash: $(BUILD_DIR)/$(TARGET).elf
	openocd -f interface/stlink.cfg  -f target/stm32f4x.cfg -c "program $(BUILD_DIR)/$(TARGET).elf verify reset exit"

#######################################
# erase
#######################################
erase: $(BUILD_DIR)/$(TARGET).elf
	openocd -f interface/stlink.cfg -f target/stm32f4x.cfg -c "init; reset halt;  mass_erase 0; exit"

#######################################
# clean up
#######################################
clean:
	rm -r $(BUILD_DIR)/*
	
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***